### ISSUE TITLE
Module 'cron-time-generator/dist/EveryTime"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

### ISSUE THREAD

**Issue by IonelLupu** [trapcodeio/cron-time#10]
When using the latest version of the package, I get this error:

```
Module '"<my-path>/node_modules/cron-time-generator/dist/EveryTime"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

1 import EveryTime from "./EveryTime";
         ~~~~~~~~~

  node_modules/cron-time-generator/dist/EveryTime.d.ts:32:1
    32 export = EveryTime;
       ~~~~~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.

```

Adding the `"allowSyntheticDefaultImports": true`  in my project doesn't fix this. Are you ok with me creating a PR in order to change from `export = EveryTime;` to `export default class EveryTime` ?

**Comment by trapcodeio** [comment]
This is supposed to work 🤔 without switching to `export default`. 

While checking the package.json I noticed the latest version types were not correctly pointed so I have fixed that.

try upgrading to the new latest version `1.3.0` and if this problem persists you can create a PR.

**Comment by trapcodeio** [comment]
@IonelLupu did this solve the issue?

**Comment by IonelLupu** [comment]
Hi @trapcodeio . Thank you for the really quick response. Sorry for my late one (didn't have time to test on the weekend),

I just updated the package and everything is ok now. Thank you very much! 😄
