### ISSUE TITLE
LICENSE file explicitly stating MIT license?

### ISSUE THREAD

**Issue by localpcguy** [trapcodeio/cron-time#14]
While the [package.json has MIT](https://github.com/trapcodeio/cron-time/blob/79c8746a125be9c327581d2cecf57c75f7b05da3/package.json#L15) stated as the license, it would also be useful to have a LICENSE file stating that explicitly. It also has the benefit of bots and other automated processes (i.e. Github) being able to determine the license and display it.

**Comment by trapcodeio** [comment]
Thank you for this.

I have also seen the pull request.. I will merge and push to npm before the next 1hr 

Am kinda far from my workstation.

**Comment by localpcguy** [comment]
Sorry, I forgot to reference this issue in the PR - thanks for package and the the quick action, we have to document all the packages we use for one of the apps I work on and link to the LICENSE, so very helpful!

**Comment by trapcodeio** [comment]
You're welcome...  I will go and put the license in my other packages. 

Thanks for letting me know about its importance.
