### ISSUE TITLE
support for everyweekendAt with more than 2 days

### ISSUE THREAD

**Issue by tx-paola** [trapcodeio/cron-time#6]
I saw that I can do:
```
cronTime.everyWeekendAt(3, 30, 0, 4));
```
to generate: 
```
30 3 * * 0,4
// At 03:30 on Sunday and Thursday
```

but I was wondering if there is an option for more than 2 days, so I can generate:
```
30 3 * * 0,2,4
// At 03:30 on Sunday, Tuesday, and Thursday
```

**Comment by trapcodeio** [comment]
Thank you for the observation.
Give me some Hours let me implement, test, and push.

**Comment by trapcodeio** [comment]
I have added `onSpecificDays` & `onSpecificDaysAt` in new  version `1.1.1`
```javascript
cronTime.onSpecificDaysAt(['sunday', 'tuesday', 'thursday'], 3, 30); 

// Result: "30 3 * * 0,2,4"
```
