### ISSUE TITLE
onSpecificDays method has wrong condition and throws error when days parameter exists

### ISSUE THREAD

**Issue by mihael998** [trapcodeio/cron-time#7]
Everytime i call onSpecificDays it throws and error because the condition is wrong.
It should be: `!Array.isArray(days) ||  days.length === 0`
Instead is: `if (!Array.isArray(days) || days.length)`

**Comment by trapcodeio** [comment]
Thank you for pointing that out.
I wonder how it passed the test the first time.

I will update the package right away.

**Comment by trapcodeio** [comment]
Fixed and updated package 🚀
