### ISSUE TITLE
Single execution

### ISSUE THREAD

**Issue by andrejcavaco** [trapcodeio/cron-time#9]
Is there a way to do a single execution, for example December 22 2022 at 3:30pm?

**Comment by trapcodeio** [comment]
Am not sure a cronjob is best for your task.
Take a look at [Node Schedule](https://www.npmjs.com/package/node-schedule), It supports **native date** and **cron expressions** too.

```js
const schedule = require('node-schedule');
const date = new Date(2012, 11, 21, 5, 30, 0);

const job = schedule.scheduleJob(date, function(){
  console.log('The world is going to end today.');
});
```
